/*
Insert initial data for Courses
*/

IF NOT EXISTS(SELECT 1 FROM [dbo].[Courses])
BEGIN
	
	INSERT INTO [dbo].[Courses]([Name]) 
	VALUES	('Hannibal'),
	 		('Introduction to Near Eastern Art and Archaeology'),
			('Out of the Past'),
			('Architecture Studio: Building in Landscapes'),
			('History of Architecture'),
			('Roman Architecture'),
			('Structures 2'),
			('The Architectural Imagination'),
			('Theory OF City Form'),
			('Aesthetics & the Philosophy OF Art'),
			('Art Through Time: A GLOBAL VIEW'),
			('Digital Photography'),
			('Foundations OF American Cyber-Culture'),
			('Introduction TO Digital Photography'),
			('Introduction TO Visual Design'),
			('Introduction TO Visual Studies'),
			('Introduction TO Visual Thinking'),
			('Italian Renaissance'),
			('Italic Calligraphy & Handwriting'),
			('Let This Be a Lesson: Heroes, Heroines & Narrative IN Paintings AT Yale'),
			('Lighting Essentials'),
			('Photography'),
			('Photography Lectures FROM the School OF Visual Arts(SVA)'),
			('SmARThistory Video Lectures'),
			('The ELEMENTS OF Drawing'),
			('Ancient AND Medieval Philosophy'),
			('Ancient Greece: City AND Society'),
			('Ancient Greece: Myth, Art & War'),
			('Ancient Greek History'),
			('Ancient Israel'),
			('Ancient Philosophy'),
			('Ancient Wisdom AND Modern Love'),
			('Classical Mythology'),
			('Classical Mythology'),
			('Concepts OF the Hero IN Greek Civilization'),
			('Epics OF Rome'),
			('Hannibal - FREE iTunes Audio'),
			('Roman Architecture'),
			('The Roman World'),
			('Virgil’s Aeneid: Anatomy OF a Classic'),
			('Demographic Trends AND Problems OF the Modern World'),
			('Cars: Past, Present & Future'),
			('Crash Course IN Design Thinking'),
			('Everything I Know'),
			('Introduction TO Visual Design'),
			('Advanced Political Economy'),
			('Against ALL Odds: Inside STATISTICS'),
			('American Capitalism: A History'),
			('American Economic History'),
			('American Economic History'),
			('Austrian Economics: An Introduction'),
			('Behavioral Finance'),
			('Capitalism: Success, Crisis AND Reform'),
			('CASE Studies IN Economic Development'),
			('Crisis, Globalization AND Economics'),
			('Development Economics'),
			('Development Economics: Macroeconomics'),
			('Economic Analysis-Micro'),
			('Economic Geography OF the Industrial World'),
			('Economic History OF the Soviet UNION'),
			('Economic STATISTICS AND Econometrics'),
			('Economics OF the Media'),
			('Energy Decisions, Markets AND Policies'),
			('Environmental Economics'),
			('Finance Theory 1'),
			('Financial Markets'),
			('Financial Markets 2011'),
			('Financial Theory'),
			('Game Theory'),
			('Game Theory IN the Social Sciences -'),
			('Game Theory AND Economics'),
			('GLOBAL Poverty AND Impact Evaluation'),
			('Great Big Ideas'),
			('Great Economists: Classical Economics AND its Forerunners'),
			('History OF Economic Theory'),
			('How TO Win AT Texas Hold ''Em'),
			('Intermediate Microeconomic Theory'),
			('International Finance'),
			('International Finance'),
			('International Political Economy'),
			('International Trade'),
			('International Trade'),
			('Introduction to Economics'),
			('Introduction to Environmental Economics and Policy'),
			('Law and Economics I'),
			('Lectures on Human Capital'),
			('Marx''s Kapital: Volumes 1 AND 2'),
			('Marxian Economics'),
			('Mexico’s Economy: CURRENT Prospects AND History'),
			('Microeconomic Theory WITH Application TO NATURAL RESOURCES'),
			('Money AND Banking'),
			('Money AND Banking'),
			('Money, Trade AND Society'),
			('Money Skills'),
			('Poker Theory AND Analytics'),
			('Political Economy AFTER the Crisis'),
			('Principles OF Economics: Microeconomics'),
			('Principles OF Economics: Macroeconomics'),
			('Principles OF Microeconomics'),
			('Principles OF Macroeconomics'),
			('Principles OF Macroeconomics'),
			('Psychology AND Economics'),
			('PUBLIC Economics'),
			('PUBLIC Economics AND Finance'),
			('Radical Capitalism'),
			('Reading Marx’s Capital: Vol 1'),
			('Reading Marx’s Capital: Vol 2'),
			('Sports Economics'),
			('The Eurozone Crisis'),
			('The Federal Reserve AND the Financial Crisis'),
			('The Future OF Money'),
			('The Austrian School OF Economics: An Introduction'),
			('The Challenge OF World Poverty'),
			('The ELEMENTS OF Economic Analysis'),
			('The POWER OF Macroeconomics'),
			('The POWER OF Mircoeconomics'),
			('Understanding DATA'),
			('World Economic History BEFORE the Industrial Revolution'),
			('World Economy IN the 20th Century'),
			('Existentialism IN Literature & Film'),
			('Creative Activism'),
			('Holocaust IN Film AND Literature'),
			('Introduction TO Film Studies'),
			('Philosophy IN Film AND Other Media'),
			('The Film Experience'),
			('Western Movies: Myth, Ideology, Genre'),
			('Child Nutrition AND Cooking'),
			('Edible Education 101 (Spring 2014)'),
			('Edible Education 101 (2015)'),
			('Edible Education 103 WITH Michael Pollan'),
			('Food AND the Environment'),
			('Food Production, PUBLIC Health, AND the Environment'),
			('Nutrition Education FOR Cancer Prevention'),
			('Organic Agriculture Theory AND Practice'),
			('Science AND Cooking: FROM Haute Cuisine TO the Science OF Soft Matter'),
			('Speak Italian WITH Your Mouth FULL'),
			('Wine'),
			('Economic Geography OF the Industrial World'),
			('Geography OF US Presidential Elections'),
			('Geography OF Europe'),
			('Geography OF World Cultures'),
			('Geopolitics: Geographical Aspects OF International Affairs'),
			('GLOBAL Geopolitics'),
			('Introduction TO Ozark Studies'),
			('World Regions, Peoples, AND States'),
			('A Tale OF Three Super Powers'),
			('African American History: Emancipation TO the Present'),
			('African-American History: Modern Freedom Struggle'),
			('American Economic History'),
			('American Economic History'),
			('American Environmental History'),
			('Ancient Greece: City AND Society'),
			('Ancient Greece: Myth, Art & War'),
			('Ancient Greek History'),
			('Ancient Israel'),
			('Asia IN the Modern World: Images & Representations'),
			('Australian Aboriginal History'),
			('Ben Franklin AND the World OF the Enlightenment'),
			('Big History'),
			('China: Traditions AND Transformations'),
			('CIA IN the Third World'),
			('Colonial AND Revolutionary America'),
			('Constitutional Convention'),
			('Economic History OF the Soviet UNION'),
			('Early Imperial Russia'),
			('Early Modern England: Politics, Religion & Society under the Tudors AND Stuarts'),
			('Emperors OF Rome'),
			('Epidemics IN Western Society Since 1600'),
			('Ethnic Relations IN the US'),
			('Europe AND the World: Wars, Empires, Nations 1648-1914'),
			('European Civilization, 1648-1945 - FREE ONLINE Video - FREE iTunes Audio - FREE iTunes Video - Course Materials  - John Merriman, Yale'),
			('European Civilization FROM the Renaissance TO the Present'),
			('European Cultural History, 1500-1815'),
			('European Cultural History, 1660-1870'),
			('European Cultural History, 1880-1920'),
			('France Since 1871'),
			('Freedom 101: Introduction TO American Constitutional History'),
			('Hannibal'),
			('Harvey Goldberg Lectures(1975-1983)'),
			('Historical Jesus'),
			('History AND Practice OF Human Rights'),
			('History OF Information'),
			('History OF Iran TO the Safavid PERIOD'),
			('History OF the Culture OF Tea IN China AND Japan'),
			('History OF the International SYSTEM'),
			('History OF MIT'),
			('History OF the Modern Middle East'),
			('History OF New York City: A Social History'),
			('History OF the United States Since 1877'),
			('History OF the World Since 1500 CE'),
			('Intellectual History OF the United States since 1865'),
			('Introduction TO African American Studies'),
			('Introduction TO Ancient Greek History'),
			('Introduction TO American Studies'),
			('Ireland IN Rebellion(1782-1916)'),
			('Latin American History through the Novel'),
			('21 HOURS OF Lectures BY Howard Zinn'),
			('Making History'),
			('Medieval British History'),
			('Medicine AND PUBLIC Health IN American History -'),
			('Modern Civilization: 1750 TO Present'),
			('Modern Jewish History'),
			('Pirates, Smugglers, AND the Modern World'),
			('Rethinking the Black Liberation Movement'),
			('Rethinking Theory IN Black Studies'),
			('Science, Magic AND Religion'),
			('The American Founders AND Their World'),
			('The American Revolution'),
			('The Americas: IDENTITY, Culture, AND POWER'),
			('The Ancient Mediterranean World'),
			('The Birth OF the Modern: Europe AND its Others'),
			('The Civil War AND Reconstruction Era, 1845-1877'),
			('The Crusades'),
			('The Early Middle Ages, 284-1000'),
			('The Great War AND Modern Philosophy'),
			('The Flowering OF the Middle Ages'),
			('The History OF PUBLIC Health'),
			('The Kennedy Half Century'),
			('The Modern World: GLOBAL History Since 1760'),
			('The Normans'),
			('The Ottoman Empire'),
			('The Peculiar Modernity OF Britain, 1848-2000'),
			('The Reformation'),
			('The Roman World'),
			('The Story OF Freedom IN America'),
			('The Vietnam War'),
			('The Vikings'),
			('US History: FROM Civil War TO Present'),
			('20th Century United States History'),
			('The Western Tradition(Video)'),
			('War, Globalization, AND Terror'),
			('World Revolutions'),
			('World Civilization TO 1500'),
			('World Civilization Since 1500'),
			('World Economic History BEFORE the Industrial Revolution'),
			('World War AND Society IN the 20th Century: World War II'),
			('British News Media Systems'),
			('Broadcast Journalism'),
			('Creative Writing: A MASTER Class'),
			('Journalistic Ethics'),
			('Magazine Writing'),
			('Press AND Society'),
			('START Writing Essays'),
			('Arabic Elementary Course'),
			('Arabic FOR Beginners 1'),
			('Ancient Greek'),
			('Ancient Languages'),
			('BASIC German'),
			('Beginner''s Chinese'),
			('Chinese Course - Seton Hall'),
			('Beginning Chinese'),
			('Beginning Chinese Reader'),
			('Intermediate Chinese'),
			('Intermediate Chinese Reader'),
			('Advanced Chinese'),
			('Advanced Chinese Reader'),
			('Brazilian Portuguese Pronunciation'),
			('Chinese Basic'),
			('Dialogue for German Learners: Beginner''s LEVEL -'),
			('Francais interactif'),
			('Elementary French 1'),
			('Elementary French 2'),
			('French'),
			('IN ACTION'),
			('French 1 & French 2 -'),
			('Icelandic ONLINE'),
			('Intermediate Chinese'),
			('Introduction TO Ancient Greek'),
			('Introduction TO Urdu Alphabet'),
			('Introduction TO Homeric Greek'),
			('Japanese Kana - Hiragana'),
			('Kanji Characters -'),
			('Mandarin Chinese Characters'),
			('Numbers AND Radicals -'),
			('ONLINE Intermediate College Korean'),
			('Pathway TO Korean: Beginning Spoken Korean FROM Zero'),
			('Russian Essentials -'),
			('Russian FOR Beginners 1'),
			('panish 1'),
			('Spanish 2'),
			('Spanish 3'),
			('Speak Italian WITH Your Mouth FULL'),
			('Thai Alphabet'),
			('A Law Student''s Toolkit'),
			('Climate Change: Law and Policy'),
			('CopyrightX'),
			('Environmental Justice and Human Rights in the Aftermath of Katrina'),
			('Environmental Law and Policy'),
			('Environmental Politics and Law'),
			('Freedom of Speech and the Press'),
			('International Environmental Law'),
			('Introduction to Copyright Law'),
			('Labor Law and Employment Discrimination'),
			('Law and Economics I'),
			('Law and Justice'),
			('Law and Legal Thought in the 21st Century'),
			('Media Law & Ethics'),
			('Philosophy of Law'),
			('Politics and Media Freedom'),
			('Progressive Alternatives: Institutional Reconstruction Today'),
			('Race, Gender and Invisibility: Why Intersectionality Matters'),
			('Renewable Energy & Alternative Fuels(Law & Policy)'),
			('Self, Serenity, and Vulnerability'),
			('Theories of Law and Society'),
			('Video Game Law'),
			('American Literature I: Beginnings to Civil War'),
			('American Passages: A Literary Survey'),
			('Approaching Shakespeare'),
			('British and American Poetry: 1900 to the Present'),
			('Chaucer'),
			('Cervantes'' Don Quixote'),
			('Contemporary Literature'),
			('Creative Reading'),
			('Creative Writing: A MASTER Class'),
			('Cultural Studies'),
			('Dante IN TRANSLATION'),
			('Darwin AND Design'),
			('D.H. Lawrence'),
			('Dracula (BY Bram Stoker)'),
			('Dune'),
			('Epics OF Rome'),
			('Existentialism IN Literature & Film'),
			('Expansive Poetics'),
			('Faeirie AND Fantasy'),
			('Fiction FOR Young Adults'),
			('FROM Gods AND Back'),
			('Genres IN Children''s Literature'),
			('George Eliot'),
			('Hemingway, Fitzgerald, Faulkner'),
			('History of Children''s Literature'),
			('Holocaust IN Film AND Literature'),
			('History OF Poetry'),
			('How Stories Seduce Us'),
			('Introduction TO Literature AND the Environment'),
			('Introduction TO Modern Japanese Literature AND Culture'),
			('Introduction TO Poetry'),
			('Introduction TO Pre-Modern Japanese Literature AND Culture'),
			('Introduction TO Theory OF Literature'),
			('Invitation TO World Literature'),
			('Jack Kerouac'),
			('Latin American History through the Novel'),
			('La Préparation du roman, IN French(1978-80)'),
			('Literary History OF the Beats'),
			('Literature AND Form'),
			('Literature AND Psychoanalysis'),
			('Milton'),
			('Lord OF the Rings I: The Road Goes Ever ON'),
			('Lord OF the Rings II: The Two Towers'),
			('Lord OF the Rings III: RETURN OF the King'),
			('Modern Poetry'),
			('NOT Shakespeare: Elizabethan AND Jacobean Popular Theatre'),
			('Old English IN CONTEXT'),
			('Oscar Wilde'),
			('Post Colonial Literature FOR Children'),
			('Restoration AND 18th Century Poetry: FROM Dryden TO Wordsworth'),
			('Rhetoric'),
			('Romanticism'),
			('Science Fiction AND Politics'),
			('Shakespeare'),
			('Shakespeare AFTER All: The Later Plays'),
			('Shakespeare''s Principal Plays'),
			('Spenser and Milton -'),
			('Survey of American Literature II'),
			('Survey of Shakespeare''s Plays'),
			('The American Novel Since 1945'),
			('The Art OF Living'),
			('The Bible AND English Literature'),
			('The Heroic Quest'),
			('The Hobbit'),
			('The Literature OF Crisis'),
			('The Lost Road(Tolkien)'),
			('The Princess Bride'),
			('The Shaping OF Middle Earth'),
			('The Silmarillion Seminar'),
			('The Tempest'),
			('The Western Canon: FROM Homer TO Milton'),
			('This Craft OF Verse: The Charles Eliot Norton Lectures'),
			('Tolkien'),
			('Tolkien''s The Book of Lost Tales: Part 1'),
			('Tolkien''s The Book OF Lost Tales: Part 2'),
			('Tolkien’s Unfinished Tales of Númenor and Middle-earth'),
			('Undergraduate Tolkien Survey'),
			('Virgil’s Aeneid: Anatomy of a Classic'),
			('Voices & Visions: The Lives & Works of 13 American Poets'),
			('Watership Down'),
			('Writing Sources'),
			('American English Speech'),
			('Old English in Context'),
			('Structure of English Words'),
			('Animation Basics'),
			('Becoming the Next Bill Nye: Writing and Hosting the Educational Show'),
			('Branding, Content & Social Media'),
			('Creating Video Games'),
			('Crisis Management: Proseminar in Public Relations'),
			('Freedom of Speech and the Press'),
			('Fundamentals of Public Speaking'),
			('Game Design'),
			('Inter-Collegiate Debating I'),
			('Media, Education, and the Marketplace'),
			('Media Research Methods'),
			('Overcoming Public Speaking Anxiety'),
			('Public Speaking II'),
			('Rhetoric'),
			('Road to the Free Digital Society'),
			('Storytelling'),
			('The Interview'),
			('The Rise of Superheroes and Their Impact On Pop Culture'),
			('Video Production'),
			('Writing for Strategic Communication'),
			('Basic Concepts of Music Theory'),
			('Dave Conservatoire(Music Theory Lessons)'),
			('Free Music Courses(Multiple Offerings)'),
			('Introduction to Pitch Systems in Tonal Music'),
			('Introduction to Theatre and Drama Arts'),
			('Introduction to World Music'),
			('Jazz and Culture'),
			('Listening to Music'),
			('Stravinsky’s Rite of Spring: Modernism, Ballet, and Riots'),
			('The Ethics of Jazz(Lecture Series)'),
			('The Language of Music'),
			('The British Lectures'),
			('The Unanswered Question: 6 Lectures on Music'),
			('A History of Philosophy'),
			('A Romp Through Ethics for Complete Beginners'),
			('A Romp Through the Philosophy of Mind'),
			('Aesthetics & Philosophy of Art -'),
			('Analytic Philosophy: Wilfrid Sellars'),
			('Ancient and Medieval Philosophy'),
			('Ancient Philosophy'),
			('Ancient Philosophy'),
			('Ancient Wisdom and Modern Love'),
			('Argument Diagramming'),
			('Aristotle: Ethics'),
			('Aristotle: Rhetoric'),
			('Authority & the Individual: Six BBC Lectures'),
			('Bioethics: An Introduction'),
			('Contemporary Issues in Philosophy of Mind & Cognition'),
			('Cosmologies of Capitalism'),
			('Critical Reasoning for Beginners'),
			('Dark Matter of the Mind'),
			('Death'),
			('Deleuze: 8 cours de philosophie'),
			('(in French)'),
			('Deleuze: Sur Spinoza'),
			('(in French)'),
			('Darwin and the Evolution of Thought'),
			('David Hume''s Central Principles'),
			('Discourse and Truth'),
			('Eight Philosophy Courses by Gilles Deleuze'),
			('Environmental Ethics'),
			('Environmental Philosophy'),
			('Epictetus'' Enchiridion - Ancient Philosophy & Peace of Mind'),
			('Epistemology'),
			('Ethics'),
			('Ethics'),
			('Ethics, an Introduction'),
			('Existentialism'),
			('Existentialism in Literature & Film'),
			('Existentialism in Literature and Film'),
			('Evidence and Ideology'),
			('Fear and Trembling in the 21st Century'),
			('Foundations of Modern Social Theor'),
			('From Gods and Back'),
			('General Philosophy'),
			('German Idealism and the 19th Century'),
			('Gödel, Escher, Bach: A Mental Space Odyssey'),
			('Great Big Ideas'),
			('Half Hour Hegel: The Complete Phenomenology of Spirit'),
			('Hegel: The Philosophy of History'),
			('Hegel''s Phenomenology of Spirit'),
			('Hegel''s Phenomenology of Spirit'),
			('Hegel''s Philosophy of Right'),
			('Hegel''s Science of Logic'),
			('20th Century Philosophy: Martin Heidegger'),
			('Heidegger Meets Van Gogh: Art, Freedom and Technology'),
			('Heidegger: Being and Time'),
			('Heidegger’s Being & Time'),
			('Heidegger''s Being and Time, Division II'),
			('History of Ancient Philosophy'),
			('History of Ancient & Medieval Philosophy'),
			('History of Christian Philosophy'),
			('History of Modern Philosophy'),
			('History of Modern Philosophy'),
			('History of Modern Philosophy'),
			('Hobbes: Leviathan and De Cive(1964)'),
			('Ideas of the 20th Century'),
			('Introduction to Indian Philosophy'),
			('Introduction to Logic'),
			('Introduction to Logic'),
			('Introduction to Philosophy'),
			('Introduction to Philosophy'),
			('Introduction to Philosophy'),
			('Introduction to Philosophy'),
			('Introduction to Philosophy'),
			('Introduction to Philosophy of Science'),
			('Introduction to Political Philosophy'),
			('Introduction to Political Philosophy(Partial)'),
			('Introduction to Political Philosophy: Study of Aristotle’s Politics'),
			('Introduction to Theory'),
			('Justice: What''s the Right Thing to Do?')
			 
	INSERT INTO [dbo].[Courses]([Name]) 
	VALUES	('Kant'),
			('Kant: Political Philosophy'),
			('Kant''s Critique of Judgment'),
			('Kant''s Critique of Pure Reason'),
			('Kant''s Critique of Pure Reason'),
			('Kant''s Critique of Pure Reason'),
			('Later Heidegger'),
			('Later Heidegger'),
			('Lecture Course in Ethical and Political Philosophy'),
			('Lecture Course in Plato'),
			('Life and Mind in Nature'),
			('Kant’s Epistemology'),
			('Knowledge and Rationality'),
			('Life, Meaning and Morality'),
			('Logic and Proofs'),
			('Machiavelli'),
			('Man, God, and Society in Western Literature'),
			('Marx''s Kapital: Volumes 1 and 2'),
			('Marxism'),
			('Marx, Nietzsche and Hegel''s Logic of Essence'),
			('Medical Ethics'),
			('Merleau-Ponty''s Phenomenology of Perception'),
			('Metaphysics'),
			('Minds, Morality and Agency'),
			('Modern Political Philosophy'),
			('Montesquieu’s The Spirit of the Laws(1966)'),
			('Natural Right'),
			('Nietzsche'),
			('Nietzsche, Beyond Good and Evil'),
			('Nietzsche and the Postmodern Condition'),
			('Nietzsche on Mind and Nature'),
			('On Romantic Love'),
			('Philosophical Issues in Brain Science'),
			('Philosophy of Mental Illness'),
			('Philosophical Problems'),
			('Philosophy of Kant'),
			('Philosophy of Plato'),
			('Philosophy of Religion'),
			('Philosophy and Human  '),
			('Philosophy and the Science of Human Nature'),
			('Philosophy in Film and Other Media'),
			('Philosophy for Beginners'),
			('Philosophy of Heidegger'),
			('Philosophy of Language'),
			('Philosophy of Law'),
			('Philosophy of Love in the Western World'),
			('Philosophy of Mind'),
			('Philosophy of Mind'),
			('Philosophy of Nature(Science)'),
			('Philosophy of the Natural Sciences'),
			('Philosophy of Religion'),
			('Philosophy of Religion'),
			('Philosophy of Society'),
			('Plato'),
			('Plato''s Apology of Socrates'),
			('Plato Apology/Crito'),
			('Plato: Gorgias'),
			('Plato: Laws'),
			('Plato: Meno'),
			('Plato, Protagoras -'),
			('Plato''s Republic'),
			('Plato''s Theaetetus'),
			('Political, Economic and Social Thought'),
			('Political Philosophy: Ideas of the 20th Century'),
			('Political Philosophy'),
			('Marx'),
			('Political Philosophy'),
			('Rousseau'),
			('Practical Reasoning'),
			('Professional Ethics'),
			('Psychology of Will'),
			('Realism in Perspective'),
			('Seventeenth Century Philosophy'),
			('Science and the Modern World'),
			('Science vs. Religion'),
			('Social and Political Philosophy'),
			('Social and Political Philosophy(Economy)'),
			('Social and Political Philosophy(Economy)'),
			('Social Theory, the Humanities & Philosophy Now'),
			('Socrates'),
			('Soren Kierkegaard'),
			('Symbolic Logic'),
			('The Analytic Tradition'),
			('The Art of Living'),
			('The Black Man in the Cosmos(One lecture)'),
			('The Central Philosophy of Tibet'),
			('The Culture of the Self'),
			('The Examined Life'),
			('The Great War and Modern Philosophy'),
			('The History of Philosophy Without Any Gaps'),
			('The History of Western Social Theory'),
			('The Human Compass'),
			('The Moral Foundations of Politics'),
			('The Nature of Causation'),
			('The Rational Mind'),
			('The Origins of Political Science'),
			('The Origins of Political Science'),
			('The Philosophy of David Hume'),
			('The Philosophy of Descartes'),
			('The Secular and The Sacred'),
			('The Self Under Siege'),
			('The Universe As We Find It'),
			('Thucydides'),
			('Truth & Subjectivity'),
			('Unveiling Reality'),
			('Vico: Seminar in Political Philosophy'),
			('Walter Kaufmann'),
			('Why the World Does Not Exist'),
			('Xenophon’s'),
			('African American Studies: Intro to African American Political Thought'),
			('American Democracy and Citizenship'),
			('British Government'),
			('Capital Punishment: Race, Poverty, & Disadvantage'),
			('Conceptual Foundations of International Politics'),
			('Climate Change: Law and Policy'),
			('Data Literacy and Data Visualization'),
			('Election 2012'),
			('Environmental Politics and Law'),
			('Faith and Globalization'),
			('Geography of US Presidential Election'),
			('Harvard Student Course on How to Resist Trump'),
			('International Political Economy'),
			('Introduction to German Politics'),
			('Introduction to Political Philosophy'),
			('Introduction to Political Philosophy: Study of Aristotle’s Politics'),
			('Justice: A Journey in Moral Reasoning'),
			('Modeling Politics'),
			('Perspectives on China(Video)'),
			('Politics and Strategy'),
			('Republicanism'),
			('Second Amendement'),
			('Seminar in Political Philosophy'),
			('Marx'),
			('Seminar in Political Philosophy'),
			('Rousseau'),
			('Sexuality and Power'),
			('Science Fiction and Politics'),
			('State of the Union 2014'),
			('The European Union in the New Millenium'),
			('The Habitable Planet: A Systems Approach to Environmental Science'),
			('The Moral Foundations of Politics'),
			('The Origins of Political Science'),
			('The Past and Future of the Left'),
			('The Politics of Educational Inequality'),
			('Ancient Israel'),
			('Apologetics 101'),
			('Biblical Hermeneutics, Old and New Testament'),
			('Biblical Theology'),
			('Buddhism and Cognitive Science'),
			('Buddhism Through its Scriptures'),
			('Buddhist Psychology'),
			('Christianity and Ethics'),
			('Christianity Through Its Scriptures'),
			('Doctrine of God'),
			('Faith and Globalization'),
			('Faith, Social Justice and Public Life'),
			('From Israelite to Jew'),
			('Genesis Through Joshua'),
			('Historical Jesus'),
			('History and Philosophy of Christian Thought'),
			('History of Christianity I'),
			('History of Christianity II'),
			('History of Christian Philosophy'),
			('History of Islamic Society'),
			('History and Nature of Apologetics'),
			('Introduction to the Old Testament(Hebrew Bible)'),
			('Introduction to the Quran: The Scripture of Islam'),
			('Introduction to New Testament History and Literature'),
			('Introduction to Religion'),
			('Jerusalem: The Holy City from Ancient Canaan t0 Modern Israel'),
			('Jews and Christians Throughout History'),
			('Literature and World of the Old Testament/Hebrew Bible'),
			('Medieval Church'),
			('Philosophy of Religion'),
			('Philosophy of Religion'),
			('Religion and its Future'),
			('Science, Magic and Religion: From Antiquity to Present'),
			('Science vs. Religion'),
			('Systematic Theology 101: Prolegomena'),
			('The Bible and English Literature'),
			('The Central Philosophy of Tibet'),
			('The Hebrew Bible'),
			('The Hebrew Scriptures in Judaism & Christianity'),
			('The Reformation'),
			('Theology of Hebrews'),
			('Cosmologies of Capitalism'),
			('Foundations of Modern Social Theor'),
			('Global Sociology'),
			('Human Development Across the Lifespan in a Social Context'),
			('Introduction to the Science of Nonviolence'),
			('Introduction to Sociology'),
			('Introduction to Sociology'),
			('Introduction to Sociology'),
			('Rethinking Feminism'),
			('Sexuality and Power'),
			('Sociological Theory'),
			('Statistics for the Social Sciences'),
			('The History of Fear'),
			('The History of Western Social Theory'),
			('The Invention of the Modern World'),
			('Sensing Place: Photography as Inquiry'),
			('Aircraft Systems Engineering'),
			('Space Flight Mechanics'),
			('Exploring Our Humanity'),
			('Introduction to Biological Anthropology'),
			('Introduction to Cultural and Social Anthropology'),
			('Witch-Hunt Persecutions'),
			('Astrobiology and Space Exploration'),
			('Astronomy 101'),
			('Exploring Black Holes: General Relativity & Astrophysics'),
			('From Chemistry to Life'),
			('From Planets to Cosmos'),
			('Frontiers and Controversies in Astrophysics'),
			('Hunting for Life in the Universe'),
			('Introduction to Astrophysics'),
			('Introduction to Cosmology'),
			('Introduction to General Astronomy'),
			('Introduction to General Astronomy'),
			('Introduction Planetary Science and Astronomy'),
			('Life in the Universe'),
			('Origins: From the Big Bang to the Emergence of Humans'),
			('Survey of Astronomy'),
			('The Accelerating Universe'),
			('The Planets'),
			('The Planets'),
			('Adolescent Health and Development'),
			('Advanced Clinical Pathophysiology(Nur 6591)'),
			('Anatomy & Physiology'),
			('Animals in Research: Law, Policy, and Humane Sciences'),
			('Animal Behavior'),
			('Animal Science'),
			('Autism and Related Disorders -'),
			('Basic Nursing Theory'),
			('Behavioral Endocrinology'),
			('Biochemistry'),
			('Biochemistry'),
			('Biochemistry for Pre-Meds'),
			('Biodiversity and the Meaning of Human Existence'),
			('Biology Beyond Genes'),
			('Biophotonics'),
			('Bioscience in the 21st Century'),
			('Brain and Behavior'),
			('Brain Structure and its Origins'),
			('Cardiovascular Grand Rounds'),
			('Case Studies in Primary Healthcare'),
			('Changing the Face of American Healthcare'),
			('Computational Molecular Biology'),
			('Darwin''s Legacy'),
			('Diet and Nutrition'),
			('Enhancing Humane Science - Improving Animal Research'),
			('Environmental Health Sciences'),
			('Evolution'),
			('Evolution and Medicine'),
			('Evolution, Ecology and Behavior'),
			('Exercise Science and Wellness'),
			('Foundations of Computational and Systems Biology'),
			('Frontiers in Biomedical Engineering'),
			('Fundamentals of Biology'),
			('General Biology 1'),
			('General Biology 1'),
			('General Biology 2'),
			('General Biology'),
			('General Biochemistry and Molecular Biology'),
			('General Human Anatomy'),
			('General Introduction to Plant Development, Form, and Function'),
			('Genetic Engineering in Medicine, Agriculture, and Law'),
			('Genomes and Diversity'),
			('Genomics & Computational Biology'),
			('Genomic Medicine'),
			('Getting Started in Crypto-EM'),
			('Global Problems of Population Growth'),
			('Growing Up in the Universe'),
			('Hacking Consciousness: Consciousness, Cognition and the Brain'),
			('Health and Culture'),
			('Health Behavior Change at the Individual, Household and Community Levels'),
			('Human Behavioral Biology'),
			('Introduction to Biochemistry'),
			('Introductory Biology'),
			('Introduction to Biology'),
			('Introduction to Biology'),
			('Introduction to Cellular & Molecular Biology'),
			('Introduction to Human Nutrition'),
			('Introduction to Human Physiology'),
			('Introduction to Immunology'),
			('Introduction to Toxicology'),
			('Introduction to Veterinary Anesthesiology'),
			('Issues in Mental Health Research in Developing Countries'),
			('Life, Concepts and Issues: Introduction to Life Sciences for Non-Science Majors'),
			('Modern Biology'),
			('Molecular and Cell Biology'),
			('Molecular Biology: Macromolecular Synthesis and Cellular Function'),
			('Molecules and Cells'),
			('Pharmacology'),
			('Plant Science'),
			('Pre-Med Primer: What Your Advisor Won''t Tell You'),
			('Principles of Human Development'),
			('Principles of Human Nutrition'),
			('Pulmonary Medical School'),
			('Replaceable You: Stem Cells and Tissue Engineering'),
			('Straight Talk About Stem Cells'),
			('Stem Cells: Policy and Ethics'),
			('The Brain: A User''s Guide'),
			('The Future of Human Health'),
			('The History of Public Health'),
			('The Stanford Mini Med School(Fall)'),
			('The Stanford Mini Med School(Winter) -'),
			('The Stanford Mini Med School(Spring)'),
			('The Stanford Mini Med School: The Heart'),
			('Urban Health in Developing Countries'),
			('Virology'),
			('Branding, Content & Social Media'),
			('Building a Business'),
			('Building a Business: Moving Your Product to the Market'),
			('Corporate Finance'),
			('Corporate Finance for Healthcare Administrators -'),
			('Crisis Management: Proseminar in Public Relations'),
			('Entrepreneurship and Business Planning'),
			('Entrepreneurship through the Lens of Venture Capital'),
			('Essentials of Advertising and Marketing'),
			('Financial Management'),
			('Global Risk Regulation'),
			('Global Supply Chain Management'),
			('Financial Planning and Money Management'),
			('Futures and Options'),
			('(Agriculture)'),
			('How to Develop Breakthrough Products and Services'),
			('How to Launch a Successful Startup Company'),
			('How to Start a Startup'),
			('Introduction to Business Administration'),
			('Introduction to Entrepreneurship'),
			('International Finance'),
			('International Taxation'),
			('Introduction to Consumer Behavior'),
			('Introduction to Strategic Management'),
			('Introductory Probability and Statistics for Business'),
			('Investment Philosophies'),
			('Money and Banking'),
			('Money and Banking'),
			('Organizational Behavior'),
			('Personal Finance'),
			('Principles of Management'),
			('Principles of Managerial Accounting'),
			('Real Estate Finance I'),
			('Real Estate Finance III'),
			('Startups'),
			('Strategic Marketing – Contemporary Issues -'),
			('Supply Chain Management & Logistics: An Intro to Principles and Concepts'),
			('Taxation of Trans-Pacific Transactions'),
			('Technology Enabled Blitzscaling'),
			('Technology Entrepreneurship'),
			('The New Entrepreneurs'),
			('The Startup Workshop'),
			('Valuation'),
			('Writing for Strategic Communication'),
			('Biochemistry 1'),
			('Biological Chemistry 1'),
			('Chemical Structure and Reactivity'),
			('Chemistry(Chemical Stoichiometry'),
			('Core Concepts in Chemistry'),
			('Crystallography'),
			('Freshman Organic Chemistry - Free Online Video - Free iTunes Video - Course Materials -'),
			('Freshman Organic Chemistry II'),
			('Fundamentals of Chemistry'),
			('General Chemistry'),
			('General Chemistry'),
			('Green Chemistry: An Interdisciplinary Approach to Sustainability'),
			('General Chemistry for Engineers'),
			('Introduction to Chemistry'),
			('Introduction to Chemical Engineering'),
			('Introduction to Green Chemistry'),
			('Introduction to Quantum Chemistry'),
			('Introduction to Solid State Chemistry'),
			('Introduction to Quantum Chemistry'),
			('Introductory Quantum Chemistry'),
			('Life, Universe & Everything: Chemistry of Our Daily Lives'),
			('Lights, Camera, Action: The Chemistry of Movies & TV'),
			('Organic Chemistry'),
			('Organic Chemistry'),
			('Organic Chemistry 1'),
			('Organic Chemistry 2'),
			('Organic Reactions and Pharmaceuticals'),
			('Organic Spectroscopy'),
			('Physical Chemistry 1'),
			('Physical Chemistry 2'),
			('Principles of Chemical Science'),
			('Advanced Algorithms'),
			('Advanced Data Structures'),
			('Advanced Operating Systems Structures and Implementation'),
			('Algorithm Design and Analysis'),
			('Algorithms for Big Data'),
			('Algorithmic Lower Bounds: Fun with Hardness Proofs'),
			('Android Development -'),
			('Artificial Intelligence'),
			('Artificial Intelligence'),
			('Artificial Intelligence - Introduction to Robotics'),
			('Artificial Intelligence -'),
			('Natural Language Processing'),
			('Artificial Intelligence -'),
			('Machine Learning'),
			('Artificial Intelligence'),
			('Basic Concepts of Operating Systems & System Programming'),
			('Bitcoin and Cryptocurrency Technologies'),
			('Bits: The Computer Science of Digital Information'),
			('Blender 3D Design'),
			('Building Dynamic Web Sites'),
			('Building Mobile Applications'),
			('Calling Bullshit in the Age of Big Data'),
			('Codecademy'),
			('Coding Together: Apps for iPhone and iPad'),
			('-2012'),
			('Coding Together'),
			('Apps for iPhone and iPad(2013)'),
			('Computational Camera and Photography'),
			('Computational Discrete Mathematics'),
			('Computer Architecture'),
			('Computer Graphics'),
			('Computer Graphics'),
			('Computer Language Engineering'),
			('Computer Networks'),
			('Computer Science: Foundations of Computer & Information Security'),
			('Computer Systems'),
			('Computer System Engineering'),
			('Computer Systems Security'),
			('CS50, Harvard''s Introductory Computer Science Course(2017)'),
			('CS50, Harvard''s Introductory Computer Science Course(2016)'),
			('CS50, Harvard''s Introductory Computer Science Course(2012)'),
			('CS50, Harvard''s Introductory Computer Science Course(2013)'),
			('CS50, Harvard''s Introductory Computer Science Course(2014)'),
			('Database Systems Design'),
			('Data Structures'),
			('Data Structures'),
			('Data Structures and Algorithms'),
			('Data Structures'),
			('Deep Learning'),
			('Deep Learning'),
			('Design and Analysis of Algorithms'),
			('Design in Computing'),
			('Developing Apps for iOS 5(iPhone & iPad)'),
			('Developing iOS 7 Apps for iPhone and iPad'),
			('Developing iOS 8 Apps with Swift'),
			('Developing iOS 9 Apps with Swift'),
			('Developing iOS 10 Apps with Swift'),
			('Developing iPad Applications for Visualization and Insight'),
			('Discrete Mathematical Structures'),
			('Discrete Mathematics and Probability Theory'),
			('Discrete Stochastic Processes'),
			('Discrete Structures'),
			('Discrete Structures'),
			('Efficient Algorithms and Intractable Problems'),
			('Foundations of Computer Graphics'),
			('Graphics Architecture'),
			('Great Insights in Computing'),
			('Higher Computing'),
			('Human-Computer Interaction Seminar'),
			('Innovative Computing'),
			('Intensive Introduction to Computer Science Using C, PHP, and JavaScrip'),
			('Introduction to AI Robotics'),
			('Introduction to Algorithms'),
			('Introduction to Computer Graphics & GPU Programming'),
			('Introduction to Computer Science and Programming in Python'),
			('Introduction to Computational Thinking and Data Science'),
			('Introduction to Computer Science and Programming(Using Python)'),
			('Introduction to Computer Science: Programming Methodology'),
			('Introduction to Computer Science: Programming Abstractions'),
			('Introduction to Computer Science: Programming Paradigms'),
			('Introduction to Computer Architecture(2013)'),
			('Introduction to Computer Architecture(2012)'),
			('Introduction to Computer Graphics'),
			('Introduction to Computing for Non-Majors'),
			('Introduction to Computing'),
			('Introduction to Electrical Engineering and Computer Science I'),
			('Introduction to Embedded Systems'),
			('Introduction to Formal Systems & Computation'),
			('Introduction to Information Studies'),
			('Introduction to iPhone Application Development'),
			('Introduction to Linux'),
			('Introduction to Problem Solving & Programming'),
			('iPhone Application Development in iOS5(Fall 2011)'),
			('iPhone Application Development(Spring 2009)'),
			('iPhone Application Development(Winter 2010)'),
			('Linux Implementation/Administration Practicum'),
			('Learning from Data: A Machine Learning Course'),
			('Local Area Network'),
			('Logic & Proofs'),
			('Machine Structures'),
			('Machine Learning'),
			('Machine Learning'),
			('Machine Learning Crash Course'),
			('Massively Parallel Computing'),
			('Mathematics for Computer Science')

	INSERT INTO [dbo].[Courses]([Name]) 
	VALUES	('Media Programming'),
			('Mobile Software Engineering'),
			('Multicore Programming Primer'),
			('Network Security'),
			('Neural Networks for Machine Learning'),
			('Operating Systems and System Programming'),
			('Performance Engineering of Software Systems'),
			('Principles of Computing'),
			('Principles of Digital Communications I'),
			('Principles of Digital Communications II'),
			('Probabilistic Systems Analysis and Applied Probability'),
			('Programming Languages and Compilers'),
			('Programming for Designers'),
			('Python'),
			('Python'),
			('Quantum Computing for the Determined'),
			('Ray Tracing for Global Illumination'),
			('Responsible Computing'),
			('Search Engines: Technology, Society and Business'),
			('Signal Processing on Databases'),
			('Software as a Service'),
			('Startups'),
			('TCP/IP'),
			('The Beauty and Joy of Computing'),
			('The Future of the Internet'),
			('The Society of Mind'),
			('The Structure and Interpretation of Computer Programs'),
			('Theory of Computation'),
			('Understanding Computers and the Internet'),
			('Virtual Reality'),
			('Visual Navigation for Flying Robots'),
			('Wide Area Networks'),
			('Wireless Networking'),
			('XML with Java'),
			('Advanced Analog Integrated Circuits'),
			('Atomistic Computer Modeling of Materials'),
			('Basic Electronics'),
			('Cellular Solids: Structure, Properties and Applications'),
			('Chemical Engineering: Process Dynamics and Controls'),
			('Communications Systems'),
			('Control Systems Engineering'),
			('Convex Optimization I'),
			('Convex Optimization 2'),
			('Digital Signal Processing'),
			('Direct Solar/Thermal to Electrical Energy Conversion Technologies'),
			('Dynamics of Machines'),
			('Dynamics and Control I'),
			('Electrical - Digital Signal Processing'),
			('Electro Magnetic Fields'),
			('Electronics & Communication Engineering - Signals and Systems'),
			('Electronic Feedback Systems'),
			('Electronic Techniques for Engineering'),
			('Electronics - High Speed Devices & Circuit'),
			('Engineering Dynamics'),
			('Engineering Ethics'),
			('Engineering Ethics'),
			('Engineering Statics'),
			('Environmental Air Pollution'),
			('Fields and Waves'),
			('Fluid Mechanics'),
			('Fundamentals of Photovoltaics'),
			('Green Supply Chain Management'),
			('Groundwater Hydrology'),
			('High-Speed Digital Design'),
			('Humanitarian Engineering'),
			('Image Processing'),
			('Information and Entropy'),
			('Information Theory and Coding'),
			('Integrated Circuit Devices'),
			('Introduction to Chemical Engineering'),
			('Introduction to Digital Integrated Circuits'),
			('Introduction to Engineering'),
			('Introduction to Engineering'),
			('Introduction'),
			('to Fluid Mechanics'),
			('Introduction to Lean Six Sigma Methods'),
			('Introduction to Linear Dynamical Systems'),
			('Introduction to Microelectronic Devices & Circuits'),
			('Introduction to Modeling and Simulation'),
			('Linear Integrated Circuits'),
			('Mechanical Engineering: Introduction to MEMS Design'),
			('Microelectronic Devices and Circuits'),
			('Microcontroller Design'),
			('Microcontroller and System-on-Chip Construction Using Verilog and Altera FPGA'),
			('Nano-to-Macro Transport Processes'),
			('Nanomanufacturing'),
			('Nonlinear Finite Element Analysis'),
			('Nuclear Engineering'),
			('Nuclear Engineering 101 Nuclear Reactions and Radiation'),
			('Optimization Models in Engineering'),
			('Pre-Engineering: Intro to Microcontrollers'),
			('The Art of Engineering'),
			('The Engineering Profession'),
			('The Fourier Transform and its Applications'),
			('Technology Entrepreneurship'),
			('Understanding Lasers and Fiberoptics'),
			('Adaptation to Climate Change'),
			('American Environmental History'),
			('Americans and the Global Forest'),
			('Australian Environmental History'),
			('Blue Planet: Introduction to Oceanography'),
			('Climate Change: Law and Policy'),
			('Education for Sustainable Living: Environment'),
			('Energy Regulations and the Environment'),
			('Environmental Economics & Policy'),
			('Environmental Economics & Policy'),
			('Environmental Law and Policy'),
			('Environmental Politics and Law'),
			('Food and the Environment'),
			('Global Warming: Understanding the Forecast -'),
			('How Climate Works'),
			('International Environmental Law'),
			('Introduction to Environmental Science'),
			('Introduction to Earthquakes, Their Causes and Effects'),
			('Introduction to Environmental Economics and Policy'),
			('Introduction to Literature and the Environment'),
			('Introduction to Permaculture'),
			('Microeconomic Theory with Application to Natural Resources'),
			('Mitigating Agriculture''s Impact'),
			('On Thin Ice: Climate Change and the Cryosphere'),
			('Radar'),
			('Renewable Energy & Alternative Fuels(Law & Policy)'),
			('Sustainable Living'),
			('The Atmosphere, the Ocean, and Environmental Change'),
			('Wildlife Ecology'),
			('Woods Energy Seminar'),
			('A First Course in Linear Algebra'),
			('Abstract Algebra'),
			('Against All Odds: Inside Statistics'),
			('Algebraic Topology: A Beginner''s Course'),
			('Analytic Geometry and Calculus'),
			('Applied Linear Algebra'),
			('Brief Calculus'),
			('Calculus 1'),
			('Calculus One'),
			('Calculus Revisited: Single Variable Calculus(1970)'),
			('Calculus Revisited: Multivariable Calculus(1970)'),
			('Calculus Revisited: Complex Variables, Differential Equations, and Linear Algebra (1972)'),
			('Causal & Statistical Reasoning'),
			('College Algebra'),
			('College Algebra'),
			('College Mathematics'),
			('Computational Science and Engineering I'),
			('Core Science Mathematics'),
			('Differential Equations'),
			('Differential & Integral Calculus'),
			('Empirical Research Methods'),
			('Engineering Statistics'),
			('Geometric Folding Algorithms:Linkages, Origami, Polyhedra'),
			('History of Mathematics'),
			('Hyperbolic Geometry'),
			('Introduction to Probability and Statistics'),
			('Introductory Probability and Statistics for Business'),
			('Introduction to Statistics and Data Analysis'),
			('Linear Algebra'),
			('Linear Algebra 1'),
			('Logic & Proofs'),
			('Mathematics: The Language of Nature'),
			('Mathematical Logic'),
			('Mathematics in India - From Vedic Period to Modern Times'),
			('Mathematics for Computer Science'),
			('Mathematics: Making the Invisible Visible'),
			('Mathematics Illuminated'),
			('Multiple View Geometry'),
			('Multivariable Calculus'),
			('Numerical Analysis'),
			('Probability and Statistics'),
			('Probability for Math Science'),
			('Rational Trigonometry'),
			('Real Analysis'),
			('Real Analysis'),
			('Regression Analysis'),
			('Sets, Counting, and Probability'),
			('Single Variable Calculus'),
			('Social Statistics'),
			('Statistical Reasoning'),
			('Statistical Reasoning I'),
			('Statistical Reasoning II'),
			('Statistics'),
			('Statistics for the Behavioral Sciences'),
			('Statistics for the Social Sciences'),
			('Statistics: Introduction to Probability'),
			('STEM Readiness'),
			('The Calculus Lifesaver'),
			('The Infinite Quest'),
			('Topics in Mathematics with Applications in Finance'),
			('Trigonometry'),
			('Vector Calculus'),
			('100 Years of Gravitational Waves'),
			('A Descriptive Introduction to Physics'),
			('Advanced Quantum Mechanics'),
			('Atomic and Optical Physics I'),
			('Atomic and Optical Physics II'),
			('Classical Field Theory'),
			('Classical Physics'),
			('Einstein''s Astrophysical Messengers'),
			('Effective Field Theory'),
			('Exploring Black Holes: General Relativity & Astrophysics'),
			('Exploring the Warped Universe'),
			('Electromagnetism and Optics'),
			('Endless Universe: Beyond the Big Bang'),
			('Fundamental Lessons from String Theory'),
			('Fundamentals of Physics'),
			('Fundamentals of Physics II'),
			('Harmony and Balance'),
			('History and Mysteries of the Universe'),
			('Inflationary Theory'),
			('Introduction to Astrophysics'),
			('Introduction to Cosmology and Particle Physics'),
			('Introduction to Cosmology'),
			('Introduction to General Astronomy'),
			('Introduction to Solar System Astronomy'),
			('Introductory Physics'),
			('Introduction to Physics'),
			('Loop Quantum Gravity'),
			('Modern Theoretical Physics: Classical Mechanics'),
			('Modern Theoretical Physics: Quantum Mechanics(2008)'),
			('Modern Theoretical Physics: Quantum Mechanics(2013)'),
			('Modern Theoretical Physics: Special Relativity'),
			('Modern Theoretical Physics: Special Relativity(2013)'),
			('Modern Theoretical Physics: Einstein'),
			('Modern Theoretical Physics: Einstein''s General Theory of Relativity(2012)'),
			('Modern Theoretical Physics: Cosmology(2009)'),
			('Modern Theoretical Physics: Cosmology(2013)'),
			('Modern Theoretical Physics: Statistical Mechanics(2009)'),
			('Modern Theoretical Physics: Statistical Mechanics(2013)'),
			('New Adventures in Spacetime'),
			('New Ideas About Dark Matter'),
			('Physics: What We Still Don''t Know'),
			('Principles of Physics'),
			('Quantum Electrodynamics'),
			('Quantum Entanglement Part 1'),
			('Quantum Entanglement Part 3'),
			('Quantum Field Theory'),
			('Quantum Mechanics'),
			('Quantum Mechanics'),
			('Quantum Physics 1'),
			('Quantum Physics 2'),
			('Quantum Physics 2'),
			('Quantum Physics Made Relatively Simple'),
			('Quantum Theory'),
			('Physics I: Classical Mechanics'),
			('Physics II:'),
			('Electricity and Magnetism'),
			('Physics III: Vibrations and Waves'),
			('Physics for Future Presidents'),
			('Physics for Scientists and Engineers'),
			('Physics for the 21st Century'),
			('Science and Cooking: From Haute Cuisine to the Science of Soft Matter'),
			('Soft X-Rays and Extreme Ultraviolet Radiation'),
			('Solid State Basics'),
			('Space, Time and Einstein'),
			('Special Relativity'),
			('Special Theory of Relativity'),
			('Stars, Galaxies, and the Universe'),
			('Statistical Mechanics I: Statistical Mechanics of Particles'),
			('Statistical Mechanics II: Statistical Physics of Fields'),
			('Stephen Hawking Lectures on Black Holes'),
			('String Theory, Black Holes, and the Laws of Nature(Video)'),
			('String Theory and Holograhic Duality'),
			('String Theory and M Theory'),
			('The Accelerating Universe'),
			('The Black Hole Information Paradox'),
			('The Character of Physical Law'),
			('The Early Universe'),
			('The Edges of the Universe'),
			('The Feynman Lectures on Physics, Vol. 1: Mainly Mechanics, Radiation, and Heat'),
			('The Mechanical Universe'),
			('The Past and Future of Unification'),
			('The World in Eleven Dimensions'),
			('Universe or Multiverse'),
			('Wave Physics'),
			('Why the World Exists'),
			('Animal Behavior'),
			('Behavioral Neuroscience Laboratory'),
			('Brain and Behavior'),
			('Brain Structure and its Origins'),
			('Buddhism and Cognitive Science'),
			('Coding and Vision I'),
			('Communication and Conflict in Families and Couples'),
			('Cultural Psychology'),
			('Developmental Psychology'),
			('Developmental Psychopathology'),
			('Environmental Psychology'),
			('Discovering Psychology'),
			('General Psychology'),
			('Great Ideas in'),
			('Psychology'),
			('Hacking Consciousness: Consciousness, Cognition and the Brain'),
			('Hallucinations'),
			('Health Psychology'),
			('Health Psychology'),
			('How to Think Like a Psychologist'),
			('Human Emotion'),
			('Industrial/Organizational Psychology'),
			('Introduction to Clinical Psychology'),
			('Introduction to Cognitive Psychology'),
			('Introduction to Cognitive Psychology'),
			('Introduction to Psychology'),
			('Introduction to Psychology'),
			('Introduction to Psychology'),
			('Introduction to Psychology'),
			('Introduction to Psychology'),
			('Manufacturing Happiness'),
			('Maps of Meaning: The Architecture of Belief(2017)'),
			('Maps of Meaning(2014)'),
			('Maps of Meaning(2016)'),
			('Maps of Meaning(1996)'),
			('Mindful Meditations'),
			('Nine Myths About Schizophrenia'),
			('Neural Networks and Biological Modeling'),
			('Neuroscience and Behavior'),
			('Neuroscience and Free Will'),
			('Personality and Its Transformations(2016)'),
			('Personality and Its Transformations(2017)'),
			('Philosophical Issues in Brain Science'),
			('Positive Psychology'),
			('Principles of Human Development'),
			('Psychology Fundamentals'),
			('Psychology of Gender'),
			('Psychology and Economics'),
			('Psychology and Religion'),
			('Psychology of Perception'),
			('Psychology of Personality'),
			('Research and Data Analysis in Psychology'),
			('Scientific Approaches to Consciousness'),
			('Sensory Systems'),
			('Social Cognition'),
			('Social Psychology'),
			('The Biology of Consciousness'),
			('The Neuronal Basis of Psychology'),
			('The New Psychology of Depression'),
			('The Psychology, Biology and Politics of Food'),
			('The Science of Psychedelics'),
			('The World of Abnormal Psychology'),
			('Epidemiology and Control of Infectious Diseases'),
			('Ethical Challenges in Public Health Interventions: Catastrophic and Routine'),
			('Public Health Statistics'),
			('Theories and Biological Basis of Substance Abuse & Addiction')

	INSERT INTO [dbo].[Courses]([Name]) 
	VALUES	('Introduction to Electricity'),
	 		('Plumbing for Beginners'),
	 		('Maths for Plumbers'),
	 		('Mixing Plumbing and Electrics for Web Designers'),
	 		('Advanced Plumbing'),
	 		('CSS for the Modern Web'),
	 		('Become an Electrician in 30 Days')

	UPDATE	[dbo].[Courses]
	SET		[Description] = [Name]
	WHERE	[Description] IS NULL

END
